version: 2
jobs:
  build:
    working_directory: ~/goplannr
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: redis:2.8.21
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv run "pip install -r requirements.txt"
      - save_cache:
          key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - '.venv'
            - '/usr/local/bin'
            - '/usr/local/lib/python3.6/site-packages'
      - run:
          command: |
            pipenv run "python manage.py makemigrations users payment content crm product sales questionnaire wallnut earnings"
            pipenv run "python manage.py migrate"
      - run:
          command: |
            pipenv run python manage.py test users.test -v 2 2> .circleci/test_output.log
            sed -e '1,10d' < .circleci/test_output.log  >> .circleci/test_report.log
            pipenv run python manage.py test crm.test -v 2 2> .circleci/test_output.log
            sed -e '1,10d' < .circleci/test_output.log  >> .circleci/test_report.log
            pipenv run python manage.py test questionnaire.test -v 2 2> .circleci/test_output.log
            sed -e '1,10d' < .circleci/test_output.log  >> .circleci/test_report.log
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - run:
          command: |
            pipenv run "python manage.py send_report"
